import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:weathergpt_mobile/models/weather_v2_parser.dart';

void main() {
  test('parses the bundled Android backend response, not the sibling v2 shape', () {
    // Generated by TestClient against this repo, with offline provider readings.
    final data = jsonDecode(File('test/fixtures/weather_android.json').readAsStringSync())
        as Map<String, dynamic>;
    final weather = parseWeatherSnapshotV2(data, cityName: 'Ahmedabad');
    expect(weather.temperatureC, 25);
    expect(weather.weatherCode, 0);
    expect(weather.humidity, 65);
    expect(weather.windKmh, 8);
    expect(weather.uvIndex, 6);
    expect(weather.aqi, 30);
    expect(weather.forecast, hasLength(1));
    expect(weather.hourly, hasLength(2));
    expect(weather.forecast.first.windKmhMax, 12);
    expect(weather.provenance.selectedSource, 'open_meteo');
    expect(weather.utcOffset, Duration.zero);
  });
}
