import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { EMULATOR_BACKEND_URL, resolveBackendUrl } from "../src/core/config/backendConfig";
import { ApiEndpoints } from "../src/core/config/apiEndpoints";
import { APP_MODES } from "../src/core/models/appMode";
import { parseWeatherSnapshotV2 } from "../src/features/weather/models/weatherV2Parser";
import { buildWeatherQuery } from "../src/features/weather/weatherStore";
import { DEFAULT_DEVELOPER_OPTIONS, DEV_SOURCE_PIN_WIRE, DevSourcePin } from "../src/features/settings/developerOptionsStore";

describe("backend URL", () => {
  it("explicit build URL wins over bundled config", () => {
    expect(resolveBackendUrl({ defineUrl: " https://weather.example.com/ ", dotenvUrl: "https://other.example.com" })).toBe(
      "https://weather.example.com",
    );
  });
  it("quoted env URL is normalized", () => {
    expect(resolveBackendUrl({ dotenvUrl: '"https://weather.example.com/"' })).toBe("https://weather.example.com");
  });
  it("missing config never silently connects to a hosted deployment", () => {
    expect(resolveBackendUrl({ defineUrl: "", dotenvUrl: " " })).toBe(EMULATOR_BACKEND_URL);
  });
});

describe("weather request", () => {
  it("all personas use the installed backend policy by default", () => {
    for (const mode of APP_MODES) {
      const query = buildWeatherQuery({ lat: 23, lon: 72, mode, dev: DEFAULT_DEVELOPER_OPTIONS });
      expect(query["requested_source"]).toBe("auto");
      expect(query["forecast_days"]).toBe(7);
      expect(query["hourly_hours"]).toBe(48);
      expect("model" in query).toBe(false);
    }
  });

  it("developer pins and horizons are sent only when enabled", () => {
    const dev = {
      ...DEFAULT_DEVELOPER_OPTIONS,
      enabled: true,
      sourcePin: DevSourcePin.AccuWeather,
      forecastDays: 3,
      hourlyHours: 24,
      supplementSecondaryFields: false,
    };
    const query = buildWeatherQuery({ lat: 23, lon: 72, mode: "researcher", dev });
    expect(query).toMatchObject({ requested_source: "accuweather", forecast_days: 3, hourly_hours: 24, supplement: false });
    const defaults = buildWeatherQuery({ lat: 23, lon: 72, mode: "researcher", dev: { ...dev, enabled: false } });
    expect(defaults["requested_source"]).toBe("auto");
    expect("supplement" in defaults).toBe(false);
  });

  it("removed providers are not offered in settings", () => {
    expect(Object.values(DevSourcePin).map((pin) => DEV_SOURCE_PIN_WIRE[pin])).toEqual(["auto", "open_meteo", "accuweather", "imd"]);
  });

  it("only declares endpoints this backend serves", () => {
    expect(Object.values(ApiEndpoints)).not.toContain("/v2/weather/catalog");
    expect(Object.values(ApiEndpoints).some((p) => p.startsWith("/v2/speech"))).toBe(false);
  });
});

describe("Android backend response", () => {
  it("parses the bundled backend fixture, not the sibling v2 shape", () => {
    // Generated by TestClient against this repo's backend, with offline provider readings.
    const data = JSON.parse(readFileSync(path.resolve(__dirname, "fixtures/weather_android.json"), "utf8"));
    const weather = parseWeatherSnapshotV2(data, { cityName: "Ahmedabad" });
    expect(weather.temperatureC).toBe(25);
    expect(weather.weatherCode).toBe(0);
    expect(weather.humidity).toBe(65);
    expect(weather.windKmh).toBe(8);
    expect(weather.uvIndex).toBe(6);
    expect(weather.aqi).toBe(30);
    expect(weather.forecast).toHaveLength(1);
    expect(weather.hourly).toHaveLength(2);
    expect(weather.forecast[0]?.windKmhMax).toBe(12);
    expect(weather.provenance.selectedSource).toBe("open_meteo");
    expect(weather.utcOffsetSeconds).toBe(0);
  });
});
